version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build: .
    volumes:
      - ".:/var/www/html"
    ports:
      - "81:80"
